### ISSUE TITLE
How to compile for x86?

### ISSUE THREAD

**Issue by zinid** [vouillon/opam-android-repository#4]
I was able to build shared objects for ARM architecture. I use the following commands (sort of):

```
ocamlfind -toolchain android ocamlopt -c prog.ml
ocamlfind -toolchain android ocamlopt -o libprog-jni.so -shared prog.o prog-jni.c
```

I pack libprog-jni.so in *.apk and Dalvik loads it and everything is fine.
However, I can't build the object for x86 CPU because my system is AMD64.
Is it possible to do using your tool?

**Comment by vouillon** [comment]
This is not possible at the moment.

For that, you would need a modified version of `ocaml-android` that uses the `x86` toolchain rather than the `arm-linux-androideabi` toolchain of the Android NDK.

**Comment by zinid** [comment]
Are there any plans to add the feature, so I can use something like:

```
ocamlfind -toolchain android-x86 ...
```

This is only a matter of convenience.
