### ISSUE TITLE
base-threads is missing

### ISSUE THREAD

**Issue by zinid** [vouillon/opam-android-repository#5]
Seems like base-threads is missing in the repository. Is it intended?

**Comment by vouillon** [comment]
Android does not provide a complete implementation of POSIX threads. In particular, `pthread_cancel` is not implemented.

Hence, OCaml system threads are not available.

**Comment by zinid** [comment]
As I understand pthread_cancel is the only stuff not implemented. Is it possible to build the package despite this function is not supported?

**Comment by zinid** [comment]
Is it hard to do? Is there a lot of things to patch?

**Comment by vouillon** [comment]
I don't think it is hard to do. I will have a look.

**Comment by zinid** [comment]
I set `SYSTHREAD_SUPPORT=true` at https://github.com/zinid/ocaml-android/blob/master/config/Makefile#L53 and removed `-no-pthread` at https://github.com/zinid/ocaml-android/blob/master/Makefile#L84. I have OCaml built, but still no thread enabled. I'm still struggling :)

**Comment by zinid** [comment]
Found the problem, I forgot to add systhreads at https://github.com/zinid/ocaml-android/blob/master/config/Makefile#L50

**Comment by zinid** [comment]
OK, don't bother, I resolved the issue myself in my fork.
